/* The following code was generated by JFlex 1.4.3 on 13-3-19 下午9:18 */

package appetizer.syntactic;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 13-3-19 下午9:18 from the specification file
 * <tt>complier.flex</tt>
 */
class Yylex implements java_cup.runtime.Scanner, Symbols {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int SINGLECOMMENT = 6;
  public static final int MULTICOMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\11\1\1\1\0\1\11\1\2\22\0\1\11\1\56\1\14"+
    "\1\0\1\3\1\66\1\54\1\0\1\43\1\44\1\12\1\63\1\51"+
    "\1\64\1\62\1\13\1\4\7\10\2\5\1\0\1\52\1\57\1\65"+
    "\1\60\2\0\6\7\21\3\1\6\2\3\1\47\1\15\1\50\1\55"+
    "\1\3\1\0\1\31\1\40\1\27\1\22\1\21\1\23\1\3\1\30"+
    "\1\26\1\3\1\41\1\36\1\3\1\33\1\25\1\20\1\3\1\32"+
    "\1\34\1\16\1\35\1\24\1\37\1\6\1\17\1\42\1\45\1\53"+
    "\1\46\1\61\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\13\3\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\34\3\36\2\37\1\4\1\0\1\40\1\41\1\42"+
    "\1\43\4\3\1\44\11\3\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\0\1\57"+
    "\1\60\1\61\1\62\1\63\1\64\1\65\1\4\2\3"+
    "\1\66\1\3\1\67\10\3\1\70\1\71\1\72\1\3"+
    "\1\73\1\74\1\3\1\75\13\3\1\76\1\77\1\100"+
    "\2\3\1\101\1\102\1\103\1\104\1\3\1\105";

  private static int [] zzUnpackAction() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\334\0\u0113\0\u014a"+
    "\0\u0181\0\u01b8\0\u01ef\0\u0226\0\334\0\u025d\0\u0294\0\u02cb"+
    "\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483"+
    "\0\334\0\334\0\334\0\334\0\334\0\334\0\334\0\334"+
    "\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\334\0\u0604"+
    "\0\u063b\0\u0672\0\u06a9\0\u06e0\0\334\0\334\0\u0717\0\334"+
    "\0\u074e\0\u0785\0\334\0\u07bc\0\u07f3\0\u082a\0\334\0\334"+
    "\0\334\0\334\0\u0861\0\u0898\0\u08cf\0\u0906\0\u014a\0\u093d"+
    "\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5"+
    "\0\334\0\334\0\334\0\334\0\334\0\334\0\u0b2c\0\334"+
    "\0\u0b63\0\334\0\u0b9a\0\334\0\334\0\334\0\334\0\334"+
    "\0\334\0\334\0\u082a\0\u0bd1\0\u0c08\0\u014a\0\u0c3f\0\u014a"+
    "\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u0df7"+
    "\0\334\0\334\0\334\0\u0e2e\0\u014a\0\u014a\0\u0e65\0\u014a"+
    "\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0faf\0\u0fe6\0\u101d"+
    "\0\u1054\0\u108b\0\u10c2\0\u014a\0\u014a\0\u014a\0\u10f9\0\u1130"+
    "\0\u014a\0\u014a\0\u014a\0\u014a\0\u1167\0\u014a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\11\1\12\2\10\1\12"+
    "\1\6\1\13\1\14\1\15\1\5\1\16\2\10\1\17"+
    "\1\10\1\20\1\21\1\10\1\22\1\23\2\10\1\24"+
    "\1\10\1\25\1\26\1\10\1\27\1\30\2\10\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\0\12\55\1\56\1\57"+
    "\51\55\2\60\1\61\7\60\1\62\55\60\1\63\1\64"+
    "\64\60\70\0\1\6\70\0\6\10\5\0\25\10\30\0"+
    "\1\65\1\0\1\66\1\0\1\65\62\0\2\12\2\0"+
    "\1\12\143\0\1\67\13\0\1\70\1\71\51\0\1\72"+
    "\4\0\6\10\5\0\1\10\1\73\23\10\27\0\6\10"+
    "\5\0\20\10\1\74\4\10\27\0\6\10\5\0\7\10"+
    "\1\75\15\10\27\0\6\10\5\0\7\10\1\76\15\10"+
    "\27\0\6\10\5\0\5\10\1\77\7\10\1\100\7\10"+
    "\27\0\6\10\5\0\7\10\1\101\2\10\1\102\12\10"+
    "\27\0\6\10\5\0\3\10\1\103\21\10\27\0\6\10"+
    "\5\0\1\104\7\10\1\105\14\10\27\0\6\10\5\0"+
    "\15\10\1\106\7\10\27\0\6\10\5\0\12\10\1\107"+
    "\12\10\27\0\6\10\5\0\14\10\1\110\10\10\77\0"+
    "\1\111\11\0\1\112\55\0\1\113\10\0\1\114\66\0"+
    "\1\115\66\0\1\116\60\0\1\117\5\0\1\120\61\0"+
    "\1\121\4\0\1\122\63\0\1\123\67\0\1\124\1\0"+
    "\1\125\61\0\1\126\3\0\1\127\1\130\66\0\1\131"+
    "\66\0\1\132\15\0\1\55\53\0\1\60\100\0\1\63"+
    "\54\0\1\63\71\0\1\65\3\0\1\65\62\0\2\133"+
    "\1\0\2\133\10\0\3\133\3\0\1\133\1\0\1\133"+
    "\6\0\1\133\31\0\6\10\5\0\2\10\1\134\22\10"+
    "\27\0\6\10\5\0\16\10\1\135\6\10\27\0\6\10"+
    "\5\0\14\10\1\136\10\10\27\0\6\10\5\0\10\10"+
    "\1\137\14\10\27\0\6\10\5\0\1\140\24\10\27\0"+
    "\6\10\5\0\15\10\1\141\7\10\27\0\6\10\5\0"+
    "\13\10\1\142\11\10\27\0\6\10\5\0\1\143\24\10"+
    "\27\0\6\10\5\0\14\10\1\144\10\10\27\0\6\10"+
    "\5\0\24\10\1\145\27\0\6\10\5\0\10\10\1\146"+
    "\14\10\27\0\6\10\5\0\10\10\1\147\14\10\27\0"+
    "\6\10\5\0\3\10\1\150\21\10\111\0\1\151\66\0"+
    "\1\152\63\0\1\153\7\0\6\10\5\0\3\10\1\154"+
    "\21\10\27\0\6\10\5\0\3\10\1\155\21\10\27\0"+
    "\6\10\5\0\4\10\1\156\20\10\27\0\6\10\5\0"+
    "\1\157\24\10\27\0\6\10\5\0\14\10\1\160\10\10"+
    "\27\0\6\10\5\0\17\10\1\161\5\10\27\0\6\10"+
    "\5\0\17\10\1\162\5\10\27\0\6\10\5\0\3\10"+
    "\1\163\21\10\27\0\6\10\5\0\7\10\1\164\15\10"+
    "\27\0\6\10\5\0\20\10\1\165\4\10\27\0\6\10"+
    "\5\0\13\10\1\166\11\10\27\0\6\10\5\0\4\10"+
    "\1\167\20\10\27\0\6\10\5\0\10\10\1\170\14\10"+
    "\27\0\6\10\5\0\14\10\1\171\10\10\27\0\6\10"+
    "\5\0\11\10\1\172\13\10\27\0\6\10\5\0\7\10"+
    "\1\173\15\10\27\0\6\10\5\0\15\10\1\174\7\10"+
    "\27\0\6\10\5\0\3\10\1\175\21\10\27\0\6\10"+
    "\5\0\23\10\1\176\1\10\27\0\6\10\5\0\3\10"+
    "\1\177\21\10\27\0\6\10\5\0\15\10\1\200\7\10"+
    "\27\0\6\10\5\0\15\10\1\201\7\10\27\0\6\10"+
    "\5\0\1\202\24\10\27\0\6\10\5\0\5\10\1\203"+
    "\17\10\27\0\6\10\5\0\5\10\1\204\17\10\27\0"+
    "\6\10\5\0\17\10\1\205\5\10\27\0\6\10\5\0"+
    "\3\10\1\206\21\10\24\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4510];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\6\1\1\11\13\1\10\11\6\1\1\11"+
    "\5\1\2\11\1\1\1\11\2\1\1\11\2\1\1\0"+
    "\4\11\16\1\6\11\1\1\1\11\1\1\1\11\1\0"+
    "\7\11\16\1\3\11\33\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private StringBuilder sb = null;


	private void err(String message) {
		System.out.println("Scanning error in line " + yyline + ", column " + yycolumn + ": " + message);
	}

	private java_cup.runtime.Symbol tok(int kind) {
		return new java_cup.runtime.Symbol(kind, yyline, yycolumn);
	}

	private java_cup.runtime.Symbol tok(int kind, Object value) {
		return new java_cup.runtime.Symbol(kind, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 50: 
          { return tok(DEC);
          }
        case 70: break;
        case 21: 
          { return tok(LESS);
          }
        case 71: break;
        case 2: 
          { /* skip */
          }
        case 72: break;
        case 5: 
          { return tok(TIMES);
          }
        case 73: break;
        case 32: 
          { return tok(MUL_ASSIGN);
          }
        case 74: break;
        case 4: 
          { return tok(NUM, new Integer(yytext()));
          }
        case 75: break;
        case 8: 
          { return tok(LPAREN);
          }
        case 76: break;
        case 18: 
          { return tok(BITXOR);
          }
        case 77: break;
        case 66: 
          { return tok(STRUCT);
          }
        case 78: break;
        case 60: 
          { return tok(VOID);
          }
        case 79: break;
        case 15: 
          { return tok(SEMICOLON);
          }
        case 80: break;
        case 67: 
          { return tok(SIZEOF);
          }
        case 81: break;
        case 64: 
          { return tok(BREAK);
          }
        case 82: break;
        case 43: 
          { return tok(SHL);
          }
        case 83: break;
        case 63: 
          { return tok(WHILE);
          }
        case 84: break;
        case 59: 
          { return tok(ELSE);
          }
        case 85: break;
        case 29: 
          { yybegin(YYINITIAL);return tok(STRING, sb.toString());
          }
        case 86: break;
        case 68: 
          { return tok(TYPEDEF);
          }
        case 87: break;
        case 11: 
          { return tok(RBRACE);
          }
        case 88: break;
        case 58: 
          { return tok(ELLIPSIS);
          }
        case 89: break;
        case 49: 
          { return tok(PTR);
          }
        case 90: break;
        case 20: 
          { return tok(GREATER);
          }
        case 91: break;
        case 51: 
          { return tok(SUB_ASSIGN);
          }
        case 92: break;
        case 61: 
          { return tok(CHAR);
          }
        case 93: break;
        case 16: 
          { return tok(BITOR);
          }
        case 94: break;
        case 25: 
          { return tok(MINUS);
          }
        case 95: break;
        case 47: 
          { return tok(INC);
          }
        case 96: break;
        case 6: 
          { return tok(DIVIDE);
          }
        case 97: break;
        case 31: 
          { yybegin(YYINITIAL);
          }
        case 98: break;
        case 55: 
          { return tok(INT);
          }
        case 99: break;
        case 62: 
          { return tok(UNION);
          }
        case 100: break;
        case 45: 
          { return tok(SHR);
          }
        case 101: break;
        case 39: 
          { return tok(AND);
          }
        case 102: break;
        case 19: 
          { return tok(NOT);
          }
        case 103: break;
        case 14: 
          { return tok(COMMA);
          }
        case 104: break;
        case 48: 
          { return tok(ADD_ASSIGN);
          }
        case 105: break;
        case 33: 
          { yybegin(MULTICOMMENT);
          }
        case 106: break;
        case 69: 
          { return tok(CONTINUE);
          }
        case 107: break;
        case 36: 
          { return tok(IF);
          }
        case 108: break;
        case 12: 
          { return tok(LBRACKET);
          }
        case 109: break;
        case 9: 
          { return tok(RPAREN);
          }
        case 110: break;
        case 30: 
          { /*do nothing*/
          }
        case 111: break;
        case 27: 
          { return tok(MOD);
          }
        case 112: break;
        case 7: 
          { tmpString = new StringBuilder(); yybegin(STRING);
          }
        case 113: break;
        case 1: 
          { throw new RuntimeException("Illegal character " + yytext() +
																		" in line " + (yyline + 1) + ", column " + (yycolumn + 1));
          }
        case 114: break;
        case 17: 
          { return tok(BITAND);
          }
        case 115: break;
        case 37: 
          { return tok(OR);
          }
        case 116: break;
        case 56: 
          { return tok(SHL_ASSIGN);
          }
        case 117: break;
        case 52: 
          { return tok(EQ);
          }
        case 118: break;
        case 41: 
          { return tok(XOR_ASSIGN);
          }
        case 119: break;
        case 34: 
          { yybegin(SINGLECOMMENT);
          }
        case 120: break;
        case 42: 
          { return tok(NE);
          }
        case 121: break;
        case 10: 
          { return tok(LBRACE);
          }
        case 122: break;
        case 53: 
          { return tok(MOD_ASSIGN);
          }
        case 123: break;
        case 38: 
          { return tok(OR_ASSIGN);
          }
        case 124: break;
        case 13: 
          { return tok(RBRACKET);
          }
        case 125: break;
        case 46: 
          { return tok(GE);
          }
        case 126: break;
        case 26: 
          { return tok(ASSIGN);
          }
        case 127: break;
        case 57: 
          { return tok(SHR_ASSIGN);
          }
        case 128: break;
        case 40: 
          { return tok(AND_ASSIGN);
          }
        case 129: break;
        case 65: 
          { return tok(RETURN);
          }
        case 130: break;
        case 54: 
          { return tok(FOR);
          }
        case 131: break;
        case 44: 
          { return tok(LE);
          }
        case 132: break;
        case 22: 
          { return tok(COMPLEMENT);
          }
        case 133: break;
        case 28: 
          { tmpString.append(yytext());
          }
        case 134: break;
        case 23: 
          { return tok(ATTRIBUTE);
          }
        case 135: break;
        case 24: 
          { return tok(PLUS);
          }
        case 136: break;
        case 3: 
          { return tok(ID, yytext());
          }
        case 137: break;
        case 35: 
          { return tok(DIV_ASSIGN);
          }
        case 138: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	{
		if (yystate() == YYCOMMENT) {
			err("Comment symbol do not match (EOF)!");
		}
		return tok(EOF, null);
	}
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
