package compiler.absyn;

public enum BinOp {
	ADD, SUB, MUL, DIV, MOD,
	LEFTSHIFT, RIGHTSHIFT, AND, XOR, OR,
	LESS, LEQ, GREATER, GEQ, EQ, NEQ, ASSIGN, 
	ADDASSIGN,SUBASSIGN, MULASSIGN, DIVASSIGN, MODASSIGN,  
	 LSHASSIGN, RSHASSIGN, ANDASSIGN, XORASSIGN, ORASSIGN
}
