package compiler.absyn;

public enum BinOp {
	ADD, SUB, MUL, DIV, MOD, LEFTSHIFT, RIGHTSHIFT, LESS, LEQ, GREATER, GEQ, EQ, NEQ, ASSIGN, MULASSIGN, DIVASSIGN, MODASSIGN, ADDASSIGN, SUBASSIGN, LSHASSIGN, RSHASSIGN, ANDASSIGN, XORASSIGN, ORASSIGN
}
